### ISSUE TITLE
AST inspection not working if code contains package declaration

### ISSUE THREAD

**Issue by kriegaex** [groovy-console/groovy-web-console#12] opened 2022-03-01 03:51 UTC
Open [this snippet](https://gwc-experiment.appspot.com/?codez=eJxtT01PwkAQve-vmBQO4McKGNEQJCZ68eIBiBdjzNBOy4btbt3dCgnpf3coTVMTD5ud9-a9NzMFxjvMCBKSPnZl_pWjD-SkD9ywP-RSbffy-340nY7vRlMhVF5YF8AXNt5JjSaTqy06Sv5rFBSrVMUYlDVCxBq9hyWl5Jwy2dq-YMA1bjS9o1On36_JB6BDIJN4-GOHowB4akYBpMqgBgOP8CAYJpRClBKG0hF89BRfULteTUKHzxn0Age_lfmG3NUZLHlBigbDOheg4I2CNhD1u8p-q-T6eALP2nqeMRhWkaiNdOAtw6yugyvpzO635Kgh2zyYz2EwltIM20adzUd0RJdwK-UELjpcK2-ms-EI14uu6wYmsOBXsbYSlfgF2lWZQA) and click any type of "Inspect AST". Result:

```none
Unable to produce AST for this phase due to earlier compilation error:
startup failed:
script.groovy: 1: unexpected token: package @ line 1, column 19.
   package apackage; package de.scrum_master.stackoverflow.q70661506
```

It looks as if GWC is adding a synthetical package name, even if there is one already.

**Comment by leonard84** [comment] 2022-03-01 21:52
Yeah, that is caused by the `EmbeddedCompiler` of Spock unconditionally adding a default package.

**Comment by leonard84** [comment] 2022-09-20 20:40
This is fixed now

**Closed by leonard84** 2022-09-20 20:40 UTC
Labels: bug
